(cl:defpackage ardrone_autonomy-srv
  (:use )
  (:export
   "FLIGHTANIM"
   "<FLIGHTANIM-REQUEST>"
   "FLIGHTANIM-REQUEST"
   "<FLIGHTANIM-RESPONSE>"
   "FLIGHTANIM-RESPONSE"
   "CAMSELECT"
   "<CAMSELECT-REQUEST>"
   "CAMSELECT-REQUEST"
   "<CAMSELECT-RESPONSE>"
   "CAMSELECT-RESPONSE"
   "RECORDENABLE"
   "<RECORDENABLE-REQUEST>"
   "RECORDENABLE-REQUEST"
   "<RECORDENABLE-RESPONSE>"
   "RECORDENABLE-RESPONSE"
   "LEDANIM"
   "<LEDANIM-REQUEST>"
   "LEDANIM-REQUEST"
   "<LEDANIM-RESPONSE>"
   "LEDANIM-RESPONSE"
  ))

